"""add current amount to goal

Revision ID: 7101a0d3d754
Revises: 2aef04fdb98b
Create Date: 2025-11-02 09:52:35.709272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7101a0d3d754'
down_revision = '2aef04fdb98b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('current_amount')

    # ### end Alembic commands ###
